load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "localized_textv1_proto",
    srcs = ["localized_text.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "localized_textv1_go_proto",
    importpath = "OlympusForge/gen/v1/localized_text",
    proto = ":localized_textv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "localized_text",
    embed = [":localized_textv1_go_proto"],
    importpath = "OlympusForge/gen/v1/localized_text",
    visibility = ["//visibility:public"],
)
