load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "codev1_proto",
    srcs = ["code.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "codev1_go_proto",
    importpath = "OlympusForge/gen/v1/code",
    proto = ":codev1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "code",
    embed = [":codev1_go_proto"],
    importpath = "OlympusForge/gen/v1/code",
    visibility = ["//visibility:public"],
)
