package registry

// Generated Tool Registry - DO NOT EDIT

var ToolRegistry = map[string]string{
	"govulncheck": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\govulncheck.cmd",
	"fleet-ls": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-ls.cmd",
	"fleet-dagger-up": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-dagger-up.cmd",
	"fleet-index": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-index.cmd",
	"gnd-handshake": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-handshake.cmd",
	"gnd-satchel-tool": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-satchel-tool.cmd",
	"git": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\git.cmd",
	"protoc-gen-go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\protoc-gen-go.cmd",
	"gnd-cert-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-cert-issue.cmd",
	"ollama": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\ollama.cmd",
	"flutter": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\flutter.cmd",
	"gnd-situs-attest": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-situs-attest.cmd",
	"gosec": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gosec.cmd",
	"mg": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\mg.cmd",
	"gnd-permit-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-permit-issue.cmd",
	"gnd-index": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-index.cmd",
	"go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\go.cmd",
	"air": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\air.cmd",
	"protoc-gen-connect-go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\protoc-gen-connect-go.cmd",
	"gnd-bond-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-bond-issue.cmd",
	"gnd-bale": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-bale.cmd",
	"fleet-daily-chronicle": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-daily-chronicle.cmd",
	"gnd-fence": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-fence.cmd",
	"gnd-clear": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-clear.cmd",
	"buf": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\buf.cmd",
	"trivy": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\trivy.cmd",
	"fleet-commit": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-commit.cmd",
	"fleet-publish": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\fleet-publish.cmd",
	"gnd-port": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-port.cmd",
	"gnd-levy": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-levy.cmd",
	"gnd-agent-class": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-agent-class.cmd",
	"george-bootstrap": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\george-bootstrap.cmd",
	"gnd-manifest-gen": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-manifest-gen.cmd",
	"gnd-dbol": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gnd-dbol.cmd",
	"gradle": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\000-bin\\gradle.cmd",
}
