load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "datetimev1_proto",
    srcs = ["datetime.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:duration_proto"],
)

go_proto_library(
    name = "datetimev1_go_proto",
    importpath = "OlympusForge/gen/v1/datetime",
    proto = ":datetimev1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "datetime",
    embed = [":datetimev1_go_proto"],
    importpath = "OlympusForge/gen/v1/datetime",
    visibility = ["//visibility:public"],
)
