load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "descriptorv1_proto",
    srcs = ["descriptor.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "descriptorv1_go_proto",
    importpath = "OlympusForge/gen/v1/descriptor",
    proto = ":descriptorv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "descriptor",
    embed = [":descriptorv1_go_proto"],
    importpath = "OlympusForge/gen/v1/descriptor",
    visibility = ["//visibility:public"],
)
