load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "snoozev1_proto",
    srcs = ["snooze.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:v3_proto",
    ],
)

go_proto_library(
    name = "snoozev1_go_proto",
    importpath = "OlympusForge/gen/v1/snooze",
    proto = ":snoozev1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:field_behavior_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:common_proto",
    ],
)

go_library(
    name = "snooze",
    embed = [":snoozev1_go_proto"],
    importpath = "OlympusForge/gen/v1/snooze",
    visibility = ["//visibility:public"],
)
