load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "structv1_proto",
    srcs = ["struct.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "structv1_go_proto",
    importpath = "OlympusForge/gen/v1/struct",
    proto = ":structv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "struct",
    embed = [":structv1_go_proto"],
    importpath = "OlympusForge/gen/v1/struct",
    visibility = ["//visibility:public"],
)
