load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "ruby_generated_pkg_explicitv1_proto",
    srcs = ["ruby_generated_pkg_explicit.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "ruby_generated_pkg_explicitv1_go_proto",
    importpath = "OlympusForge/gen/v1/ruby_generated_pkg_explicit",
    proto = ":ruby_generated_pkg_explicitv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "ruby_generated_pkg_explicit",
    embed = [":ruby_generated_pkg_explicitv1_go_proto"],
    importpath = "OlympusForge/gen/v1/ruby_generated_pkg_explicit",
    visibility = ["//visibility:public"],
)
