load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ackhandler",
    srcs = [
        "received_packet_handler.go",
        "sent_packet_handler.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0/internal/mocks/ackhandler",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0:__subpackages__"],
    deps = [
        "@com_github_quic_go_quic_go//internal/ackhandler:go_default_library",
        "@com_github_quic_go_quic_go//internal/protocol:go_default_library",
        "@com_github_quic_go_quic_go//internal/wire:go_default_library",
        "@org_uber_go_mock//gomock:go_default_library",
    ],
)
