load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "metric_servicev1_proto",
    srcs = ["metric_service.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:v3_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:rpc_proto",
        "@com_google_protobuf//:empty_proto",
    ],
)

go_proto_library(
    name = "metric_servicev1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "OlympusForge/gen/v1/metric_service",
    proto = ":metric_servicev1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:annotations_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:client_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:field_behavior_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:metric_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:monitored_resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:common_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:metric_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:status_proto",
    ],
)

go_library(
    name = "metric_service",
    embed = [":metric_servicev1_go_proto"],
    importpath = "OlympusForge/gen/v1/metric_service",
    visibility = ["//visibility:public"],
)
