load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "valuev1_proto",
    srcs = ["value.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:struct_proto",
    ],
)

go_proto_library(
    name = "valuev1_go_proto",
    importpath = "OlympusForge/gen/v1/value",
    proto = ":valuev1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "value",
    embed = [":valuev1_go_proto"],
    importpath = "OlympusForge/gen/v1/value",
    visibility = ["//visibility:public"],
)
