load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "commonv1_proto",
    srcs = ["common.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "commonv1_go_proto",
    importpath = "OlympusForge/gen/v1/common",
    proto = ":commonv1_proto",
    visibility = ["//visibility:public"],
    deps = ["//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:distribution_proto"],
)

go_library(
    name = "common",
    embed = [":commonv1_go_proto"],
    importpath = "OlympusForge/gen/v1/common",
    visibility = ["//visibility:public"],
)
