load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "conformance",
    srcs = ["tools.go"],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/connectrpc/connect-go-1.18.1/internal/conformance",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/connectrpc/connect-go-1.18.1:__subpackages__"],
)
