load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "anyv1_proto",
    srcs = ["any.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "anyv1_go_proto",
    importpath = "OlympusForge/gen/v1/any",
    proto = ":anyv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "any",
    embed = [":anyv1_go_proto"],
    importpath = "OlympusForge/gen/v1/any",
    visibility = ["//visibility:public"],
)
