load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "internal_optionsv1_proto",
    srcs = ["internal_options.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

go_proto_library(
    name = "internal_optionsv1_go_proto",
    importpath = "OlympusForge/gen/v1/internal_options",
    proto = ":internal_optionsv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "internal_options",
    embed = [":internal_optionsv1_go_proto"],
    importpath = "OlympusForge/gen/v1/internal_options",
    visibility = ["//visibility:public"],
)
