load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "emptyv1_proto",
    srcs = ["empty.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "emptyv1_go_proto",
    importpath = "OlympusForge/gen/v1/empty",
    proto = ":emptyv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "empty",
    embed = [":emptyv1_go_proto"],
    importpath = "OlympusForge/gen/v1/empty",
    visibility = ["//visibility:public"],
)
