package registry

// Generated Tool Registry - DO NOT EDIT

var ToolRegistry = map[string]string{
	"govulncheck": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\govulncheck.cmd",
	"fleet-ls": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-ls.cmd",
	"fleet-dagger-up": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-dagger-up.cmd",
	"fleet-index": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-index.cmd",
	"gnd-handshake": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-handshake.cmd",
	"gnd-satchel-tool": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-satchel-tool.cmd",
	"git": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\git.cmd",
	"protoc-gen-go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\protoc-gen-go.cmd",
	"gnd-cert-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-cert-issue.cmd",
	"ollama": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\ollama.cmd",
	"flutter": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\flutter.cmd",
	"gnd-situs-attest": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-situs-attest.cmd",
	"gosec": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gosec.cmd",
	"mg": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\mg.cmd",
	"gnd-permit-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-permit-issue.cmd",
	"gnd-index": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-index.cmd",
	"go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\go.cmd",
	"air": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\air.cmd",
	"protoc-gen-connect-go": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\protoc-gen-connect-go.cmd",
	"gnd-bond-issue": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-bond-issue.cmd",
	"gnd-bale": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-bale.cmd",
	"fleet-daily-chronicle": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-daily-chronicle.cmd",
	"gnd-fence": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-fence.cmd",
	"gnd-clear": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-clear.cmd",
	"buf": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\buf.cmd",
	"trivy": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\trivy.cmd",
	"fleet-commit": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-commit.cmd",
	"fleet-publish": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\fleet-publish.cmd",
	"gnd-port": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-port.cmd",
	"gnd-levy": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-levy.cmd",
	"gnd-agent-class": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-agent-class.cmd",
	"george-bootstrap": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\george-bootstrap.cmd",
	"gnd-manifest-gen": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-manifest-gen.cmd",
	"gnd-dbol": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gnd-dbol.cmd",
	"gradle": "C:\\aAntigravitySpace\\OlympusForge\\90000-Enablement-Labs\\000-Tools\\990-Execution-Hub\\gradle.cmd",
}
