load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "check_errorv1_proto",
    srcs = ["check_error.proto"],
    visibility = ["//visibility:public"],
    deps = ["//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:rpc_proto"],
)

go_proto_library(
    name = "check_errorv1_go_proto",
    importpath = "OlympusForge/gen/v1/check_error",
    proto = ":check_errorv1_proto",
    visibility = ["//visibility:public"],
    deps = ["//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:status_proto"],
)

go_library(
    name = "check_error",
    embed = [":check_errorv1_go_proto"],
    importpath = "OlympusForge/gen/v1/check_error",
    visibility = ["//visibility:public"],
)
