load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "labelv1_proto",
    srcs = ["label.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "labelv1_go_proto",
    importpath = "OlympusForge/gen/v1/label",
    proto = ":labelv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "label",
    embed = [":labelv1_go_proto"],
    importpath = "OlympusForge/gen/v1/label",
    visibility = ["//visibility:public"],
)
