load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "cmd_lib",
    srcs = ["corpus.go"],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0/fuzzing/transportparameters/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_quic_go_quic_go//fuzzing/internal/helper:go_default_library",
        "@com_github_quic_go_quic_go//fuzzing/transportparameters:go_default_library",
        "@com_github_quic_go_quic_go//internal/protocol:go_default_library",
        "@com_github_quic_go_quic_go//internal/wire:go_default_library",
        "@org_golang_x_exp//rand:go_default_library",
    ],
)

go_binary(
    name = "cmd",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)
