load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "http_requestv1_proto",
    srcs = ["http_request.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:duration_proto"],
)

go_proto_library(
    name = "http_requestv1_go_proto",
    importpath = "OlympusForge/gen/v1/http_request",
    proto = ":http_requestv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "http_request",
    embed = [":http_requestv1_go_proto"],
    importpath = "OlympusForge/gen/v1/http_request",
    visibility = ["//visibility:public"],
)
