load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "resourcesv1_proto",
    srcs = ["resources.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "@com_google_protobuf//:api_proto",
    ],
)

go_proto_library(
    name = "resourcesv1_go_proto",
    importpath = "OlympusForge/gen/v1/resources",
    proto = ":resourcesv1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:auth_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:documentation_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:endpoint_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:monitored_resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:monitoring_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:quota_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:usage_proto",
    ],
)

go_library(
    name = "resources",
    embed = [":resourcesv1_go_proto"],
    importpath = "OlympusForge/gen/v1/resources",
    visibility = ["//visibility:public"],
)
