load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "quaternionv1_proto",
    srcs = ["quaternion.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "quaternionv1_go_proto",
    importpath = "OlympusForge/gen/v1/quaternion",
    proto = ":quaternionv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "quaternion",
    embed = [":quaternionv1_go_proto"],
    importpath = "OlympusForge/gen/v1/quaternion",
    visibility = ["//visibility:public"],
)
