load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "monitored_resourcev1_proto",
    srcs = ["monitored_resource.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "@com_google_protobuf//:struct_proto",
    ],
)

go_proto_library(
    name = "monitored_resourcev1_go_proto",
    importpath = "OlympusForge/gen/v1/monitored_resource",
    proto = ":monitored_resourcev1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:label_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:launch_stage_proto",
    ],
)

go_library(
    name = "monitored_resource",
    embed = [":monitored_resourcev1_go_proto"],
    importpath = "OlympusForge/gen/v1/monitored_resource",
    visibility = ["//visibility:public"],
)
