load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "attribute_contextv1_proto",
    srcs = ["attribute_context.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:struct_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "attribute_contextv1_go_proto",
    importpath = "OlympusForge/gen/v1/attribute_context",
    proto = ":attribute_contextv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "attribute_context",
    embed = [":attribute_contextv1_go_proto"],
    importpath = "OlympusForge/gen/v1/attribute_context",
    visibility = ["//visibility:public"],
)
