load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "calendar_periodv1_proto",
    srcs = ["calendar_period.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "calendar_periodv1_go_proto",
    importpath = "OlympusForge/gen/v1/calendar_period",
    proto = ":calendar_periodv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "calendar_period",
    embed = [":calendar_periodv1_go_proto"],
    importpath = "OlympusForge/gen/v1/calendar_period",
    visibility = ["//visibility:public"],
)
