load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "late_loaded_optionv1_proto",
    srcs = ["late_loaded_option.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

go_proto_library(
    name = "late_loaded_optionv1_go_proto",
    importpath = "OlympusForge/gen/v1/late_loaded_option",
    proto = ":late_loaded_optionv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "late_loaded_option",
    embed = [":late_loaded_optionv1_go_proto"],
    importpath = "OlympusForge/gen/v1/late_loaded_option",
    visibility = ["//visibility:public"],
)
