package generator

import (
	"fmt"
	"strings"

	"github.com/VelociKey/OlympusFabric/20000-MCP-Servers/OlympusFabric/pkg/ir"
)

// PSGenerator produces PowerShell scripts to materialize a workspace structure
type PSGenerator struct{}

func NewPSGenerator() *PSGenerator {
	return &PSGenerator{}
}

func (g *PSGenerator) FormatName() string {
	return "ps1"
}

func (g *PSGenerator) FileExtension() string {
	return ".ps1"
}

func (g *PSGenerator) Generate(node *ir.Node) (string, error) {
	var sb strings.Builder
	sb.WriteString("# Automatically generated by WraithFabric\n")
	sb.WriteString("# Purpose: Materialize Workspace Structure\n\n")

	for _, child := range node.Children {
		content, err := g.generateItem(child, ".")
		if err != nil {
			return "", err
		}
		sb.WriteString(content)
	}

	return sb.String(), nil
}

func (g *PSGenerator) generateItem(n *ir.Node, parentPath string) (string, error) {
	name := n.GetAttributeString("name")
	if n.Type == ir.NodeRule {
		// In our workspace grammar, top level rules are directories
		name = n.GetAttributeString("name")
		path := parentPath + "/" + name

		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("New-Item -ItemType Directory -Path \"%s\" -Force | Out-Null\n", path))

		for _, child := range n.Children {
			content, err := g.generateItem(child, path)
			if err != nil {
				return "", err
			}
			sb.WriteString(content)
		}
		return sb.String(), nil
	}

	// Internal nodes in the workspace grammar
	switch n.Type {
	case ir.NodeSequence, ir.NodeChoice:
		var sb strings.Builder
		for _, child := range n.Children {
			content, err := g.generateItem(child, parentPath)
			if err != nil {
				return "", err
			}
			sb.WriteString(content)
		}
		return sb.String(), nil

	case ir.NodeReference:
		// Reference to another rule (nested dir/file)
		refName := n.GetAttributeString("name")
		path := parentPath + "/" + refName
		return fmt.Sprintf("New-Item -ItemType Directory -Path \"%s\" -Force | Out-Null\n", path), nil

	case ir.NodeLiteral:
		litName := n.GetAttributeString("value")
		path := parentPath + "/" + litName
		return fmt.Sprintf("New-Item -ItemType Directory -Path \"%s\" -Force | Out-Null\n", path), nil

	default:
		return "", nil // Skip descriptions or unknown metadata for shell scripts
	}
}
