package generator

import (
	"fmt"
	"strings"

	"OlympusForge/20000-Context-Bridges/000-OlympusFabric/P0000-pkg/000-ir"
)

// PSGenerator (PowerShell Generator) produces scripts to materialize file structures.
type PSGenerator struct{}

func NewPSGenerator() *PSGenerator {
	return &PSGenerator{}
}

func (g *PSGenerator) FormatName() string {
	return "powershell"
}

func (g *PSGenerator) FileExtension() string {
	return "ps1"
}

func (g *PSGenerator) Generate(node *ir.Node) (string, error) {
	if node.Type != ir.NodeRoot {
		return "", fmt.Errorf("expected root node, got %s", node.Type)
	}

	var sb strings.Builder
	sb.WriteString("# Automatically generated by WraithFabric\n")
	sb.WriteString("# Purpose: Materialize Workspace Structure\n\n")

	for _, child := range node.Children {
		content, err := g.generateItem(child, ".")
		if err != nil {
			return "", err
		}
		sb.WriteString(content)
	}

	return sb.String(), nil
}

func (g *PSGenerator) generateItem(n *ir.Node, parentPath string) (string, error) {
	name, _ := n.Attributes["name"].(string)
	currentPath := fmt.Sprintf("%s/%s", parentPath, name)

	var sb strings.Builder

	switch n.Type {
	case ir.NodeRule: // Treat Rule as Workspace/Root
		sb.WriteString(fmt.Sprintf("New-Item -ItemType Directory -Force -Path \"%s\"\n", currentPath))
		for _, child := range n.Children {
			content, err := g.generateItem(child, currentPath)
			if err != nil {
				return "", err
			}
			sb.WriteString(content)
		}

	case ir.NodeLiteral: // Treat Literal as File content or name
		sb.WriteString(fmt.Sprintf("New-Item -ItemType File -Force -Path \"%s\"\n", currentPath))

	case ir.NodeReference: // Treat Reference as Directory
		sb.WriteString(fmt.Sprintf("New-Item -ItemType Directory -Force -Path \"%s\"\n", currentPath))
		for _, child := range n.Children {
			content, err := g.generateItem(child, currentPath)
			if err != nil {
				return "", err
			}
			sb.WriteString(content)
		}
	}

	return sb.String(), nil
}
