load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "metricv1_proto",
    srcs = ["metric.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:v3_proto",
    ],
)

go_proto_library(
    name = "metricv1_go_proto",
    importpath = "OlympusForge/gen/v1/metric",
    proto = ":metricv1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:label_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:metric_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:monitored_resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/monitoring/v3:common_proto",
    ],
)

go_library(
    name = "metric",
    embed = [":metricv1_go_proto"],
    importpath = "OlympusForge/gen/v1/metric",
    visibility = ["//visibility:public"],
)
