load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "field_behaviorv1_proto",
    srcs = ["field_behavior.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

go_proto_library(
    name = "field_behaviorv1_go_proto",
    importpath = "OlympusForge/gen/v1/field_behavior",
    proto = ":field_behaviorv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "field_behavior",
    embed = [":field_behaviorv1_go_proto"],
    importpath = "OlympusForge/gen/v1/field_behavior",
    visibility = ["//visibility:public"],
)
