load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "dagger",
    srcs = ["dagger.gen.go"],
    importpath = "olympus.fleet/00SDLC/OlympusForge/70000-Environmental-Harness/dagger/lib/dagger",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_khan_genqlient//graphql:go_default_library",
        "@com_github_vektah_gqlparser_v2//gqlerror:go_default_library",
        "@io_dagger_dagger//querybuilder:go_default_library",
        "@io_opentelemetry_go_otel//:go_default_library",
        "@io_opentelemetry_go_otel//propagation:go_default_library",
        "@io_opentelemetry_go_otel_trace//:go_default_library",
    ],
)
