load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "linkedlist",
    srcs = ["linkedlist.go"],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0/internal/utils/linkedlist",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0:__subpackages__"],
)
