load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "baggage",
    srcs = [
        "baggage.go",
        "context.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/opentelemetry/otel-v1.42.0/internal/baggage",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/opentelemetry/otel-v1.42.0:__subpackages__"],
)

go_test(
    name = "baggage_test",
    srcs = ["context_test.go"],
    embed = [":baggage"],
    deps = [
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
    ],
)
