load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "ruby_generated_code_proto2v1_proto",
    srcs = ["ruby_generated_code_proto2.proto"],
    visibility = ["//visibility:public"],
    deps = ["//:root_proto"],
)

go_proto_library(
    name = "ruby_generated_code_proto2v1_go_proto",
    importpath = "OlympusForge/gen/v1/ruby_generated_code_proto2",
    proto = ":ruby_generated_code_proto2v1_proto",
    visibility = ["//visibility:public"],
    deps = ["//:ruby_generated_code_proto2_import.proto"],
)

go_library(
    name = "ruby_generated_code_proto2",
    embed = [":ruby_generated_code_proto2v1_go_proto"],
    importpath = "OlympusForge/gen/v1/ruby_generated_code_proto2",
    visibility = ["//visibility:public"],
)
