load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "congestion",
    srcs = [
        "bandwidth.go",
        "clock.go",
        "cubic.go",
        "cubic_sender.go",
        "hybrid_slow_start.go",
        "interface.go",
        "pacer.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0/internal/congestion",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0:__subpackages__"],
    deps = [
        "@com_github_quic_go_quic_go//internal/protocol:go_default_library",
        "@com_github_quic_go_quic_go//internal/utils:go_default_library",
    ],
)
