load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "otel-v1_42_0",
    srcs = [
        "doc.go",
        "error_handler.go",
        "handler.go",
        "internal_logging.go",
        "metric.go",
        "propagation.go",
        "trace.go",
        "version.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/opentelemetry/otel-v1.42.0",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_go_logr_logr//:go_default_library",
        "@io_opentelemetry_go_otel//internal/global:go_default_library",
        "@io_opentelemetry_go_otel//propagation:go_default_library",
        "@io_opentelemetry_go_otel_metric//:go_default_library",
        "@io_opentelemetry_go_otel_trace//:go_default_library",
    ],
)

go_test(
    name = "otel-v1_42_0_test",
    srcs = [
        "handler_test.go",
        "internal_logging_test.go",
        "metric_test.go",
        "trace_test.go",
        "version_test.go",
    ],
    embed = [":otel-v1_42_0"],
    deps = [
        "@com_github_go_logr_stdr//:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@io_opentelemetry_go_otel//:go_default_library",
        "@io_opentelemetry_go_otel_metric//:go_default_library",
        "@io_opentelemetry_go_otel_metric//embedded:go_default_library",
        "@io_opentelemetry_go_otel_metric//noop:go_default_library",
        "@io_opentelemetry_go_otel_trace//:go_default_library",
        "@io_opentelemetry_go_otel_trace//embedded:go_default_library",
        "@io_opentelemetry_go_otel_trace//noop:go_default_library",
    ],
)
