load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "wire",
    srcs = [
        "ack_frame.go",
        "ack_range.go",
        "connection_close_frame.go",
        "crypto_frame.go",
        "data_blocked_frame.go",
        "datagram_frame.go",
        "extended_header.go",
        "frame.go",
        "frame_parser.go",
        "handshake_done_frame.go",
        "header.go",
        "log.go",
        "max_data_frame.go",
        "max_stream_data_frame.go",
        "max_streams_frame.go",
        "new_connection_id_frame.go",
        "new_token_frame.go",
        "path_challenge_frame.go",
        "path_response_frame.go",
        "ping_frame.go",
        "pool.go",
        "reset_stream_frame.go",
        "retire_connection_id_frame.go",
        "short_header.go",
        "stop_sending_frame.go",
        "stream_data_blocked_frame.go",
        "stream_frame.go",
        "streams_blocked_frame.go",
        "transport_parameters.go",
        "version_negotiation.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0/internal/wire",
    visibility = ["//00SDLC/OlympusForge/81200-Logic-Libraries/quic-go/quic-go-0.50.0:__subpackages__"],
    deps = [
        "@com_github_quic_go_quic_go//internal/protocol:go_default_library",
        "@com_github_quic_go_quic_go//internal/qerr:go_default_library",
        "@com_github_quic_go_quic_go//internal/utils:go_default_library",
        "@com_github_quic_go_quic_go//quicvarint:go_default_library",
    ],
)
