load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "message_setv1_proto",
    srcs = ["message_set.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "message_setv1_go_proto",
    importpath = "OlympusForge/gen/v1/message_set",
    proto = ":message_setv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "message_set",
    embed = [":message_setv1_go_proto"],
    importpath = "OlympusForge/gen/v1/message_set",
    visibility = ["//visibility:public"],
)
